name: build jswasi

on:
  push:
    branches:
      - "**"
      - "!main"
  pull_request:
  workflow_call:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      DEBIAN_FRONTEND: "noninteractive"
      TYPESCRIPT_VERSION: "7.0.2"
    container:
      image: debian:trixie
    steps:
      - name: Install dependencies
        run: apt-get -qqy update > /dev/null && apt-get -qqy install node-typescript make esbuild gettext-base npm wget > /dev/null
      - name: Install TypeScript
        run: npm install -g typescript@$TYPESCRIPT_VERSION
      - name: Checkout sources
        uses: actions/checkout@v7
      - name: Build jswasi
        run: make MINIFY=1 standalone
      - name: Test jswasi
        run: make test
      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: jswasi
          path: ./dist/
